### ISSUE TITLE
项目下载失败问题

### ISSUE THREAD

**Issue by Liangll2145** [liyupi/ceshiya#1]
鱼皮大佬
为啥我在控制台运行“npm run dev”的时候会找不到umi依赖呢？
我在执行”npm install“下载依赖时，出现了各种依赖冲突问题
所以我直接执行了”npm install --legacy-peer-deps“来下载依赖
导致后面出现了一系列问题。。是依赖版本不匹配的原因吗？😮

**Comment by liyupi** [comment]
node 用 16 版本试试，或者 Npm 强制安装依赖。

**Comment by Liangll2145** [comment]
运行成功了！感谢鱼皮大佬的指导
我node换了16版本
npm install --force安装了依赖
我之前运行时用的node是18版本，估计是这个问题

**Comment by jason1216219** [comment]
我用16的版本不行
